[jenkins] Moved data source from openshift to jenkins
Ladicek/rourka pull request #2
Opened 2017-12-20 09:32 UTC by mocenas

Changed rourka to get data from jenkins instead from openshift.
Added possibility to run builds from rourka

2017-12-20 10:18 UTC, Ladicek requested changes
Please fix the code style, too. (Opening braces always on the same line, spaces around assignment operator, etc.)

Also please cut the crap (`AbstractValueTransfer`???), especially when it comes to mutable objects. No JavaBeans.

Otherwise mostly look good. I will merge this when I'm finished with the refactoring -- the dashboard comes last, even though you were able to finish it first :-)

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/java/com/github/ladicek/rourka/BuildResource.java
> +        jenkinsBuildRunner = new JenkinsBuildRunner(new JenkinsRequestHandler(httpClient));
Shouldn't be a field, just a local variable.

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/java/com/github/ladicek/rourka/jenkins/JenkinsAuthorizedHttpClientProducer.java
> +        String encodedCredentials = DatatypeConverter.printBase64Binary(authStr.getBytes("utf-8"));
Use `java.util.Base64`.

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/java/com/github/ladicek/rourka/jenkins/JenkinsDataProvider.java
> +    private Boolean readBooleanOrNull(JsonObject object, String attribute)
These two methods have very similar names, but treat `null` values very differently.

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/java/com/github/ladicek/rourka/jenkins/JenkinsProperties.java
> +            ClassLoader loader = JenkinsProperties.class.getClassLoader();
This won't work. I will want to store the credentials into an OpenShift secret, which will be exposed either as environment variables or a file. Probably a file.

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/java/com/github/ladicek/rourka/jenkins/JenkinsRequestHandler.java
> +    public JenkinsRequestHandler(HttpClient httpClient) throws Exception{
Why do you `@Inject` the HTTP client above, then?

2017-12-20 10:18 UTC, Ladicek commented on dashboard/src/main/resources/jenkins.properties
> +jenkins.apiToken=3bf6ab02b4928a54c043cbb14483199c
Don't publish secrets! Delete this file from the PR and if this is real token, contact someone to invalidate it right away.

2017-12-20 10:32 UTC, Ladicek commented
Oh, one more thing. I don't recall if the code already deals with it or not, but there will be Jenkins jobs _without_ the JSON in description. Some kind of "support" jobs. That's okay and expected; these jobs should simply be skipped, they won't be reported in the dashboard.

2017-12-20 20:11 UTC, Ladicek commented
Actually, one other question: the original approach of authenticating to Jenkins using the service account's token worked just fine. Why did you change it?

2017-12-21 08:25 UTC, mocenas commented
I changed the authentication because the authenticating thought service account's token logged user in as a service account -> which has read only access so it cannot run builds. 
I was unable to change priviledge to a service account so I changed auth. to be able to run builds

2017-12-21 10:48 UTC, Ladicek commented
Hmm, makes sense. I think it should be doable, but let's keep your change for now. I'll investigate later.

2017-12-21 10:51 UTC, mocenas commented
Well am sorry. I already investigated it deeper and found out that it is doable and I done it. So in my new version it is again done by token authentication.

2017-12-21 10:52 UTC, Ladicek commented
Nice, thanks! :-)

2017-12-21 12:56 UTC, mocenas commented
Ok I changed indentation from tabs to spaces

2018-01-16 19:27 UTC, Ladicek commented
I've merged this locally and did a significant refactoring. Closing this PR, but none of this is actually dropped. Thanks!

2018-01-16 19:27 UTC, closed without merging